// Builds screens.gen.js: the real app screens of the store visuals (store/screens.mjs),
// localized with the `app` texts of i18n.js, in "anim" mode (ids + state layers the film animates).
// Run after editing i18n.js or store/screens.mjs (render.mjs runs it automatically).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import { SCREEN_DEFS, SCREEN_FR, screenLookup, screenReport, screenSms } from "../screens.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const sandbox = { window: {} };
vm.runInNewContext(readFileSync(`${here}/i18n.js`, "utf8"), sandbox);
const I18N = sandbox.window.WC_I18N;

// Missing keys fall back to French so a half-translated locale still renders.
const merge = (base, over) => {
  if (Array.isArray(base) || typeof base !== "object" || base === null) return over ?? base;
  const out = { ...base };
  for (const k of Object.keys(over ?? {})) out[k] = merge(base[k], over[k]);
  return out;
};

const screens = {};
for (const [lang, L] of Object.entries(I18N)) {
  const S = merge(SCREEN_FR, L.app);
  screens[lang] = {
    lookup: screenLookup({ S, anim: true }),
    report: screenReport({ S, anim: true }),
    sms: screenSms({ S, anim: true }),
  };
}

writeFileSync(`${here}/screens.gen.js`,
  `// Generated by build-screens.mjs — do not edit.\nwindow.WC_SCREEN_DEFS = ${JSON.stringify(SCREEN_DEFS)};\nwindow.WC_SCREENS = ${JSON.stringify(screens)};\n`);
console.log(`→ screens.gen.js (${Object.keys(screens).join(", ")})`);
